# Generated by Django 6.0.3 on 2026-04-03 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='gallery.image'),
            preserve_default=False,
        ),
    ]
