# Generated by Django 6.0.3 on 2026-04-16 23:46

from django.db import migrations

def create_data(apps, schema_editor):
    Tag = apps.get_model('gallery', 'Tag')

    Tag.objects.create(tag = "summer")
    Tag.objects.create(tag = "fall")
    Tag.objects.create(tag = "winter")
    Tag.objects.create(tag = "spring")



class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_comment_image'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
